# https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '5 22 * * Sun'        
    
env:
  WEB_HOOKS: ${{ secrets.WEB_HOOKS }}
  WEB_HOOKS_SCRETT: ${{ secrets.WEB_HOOKS_SCRETT }}
  
jobs:
  build:

    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        
    - run: yarn
    - run: yarn schedule
